In [12]:
import pandas as pd
from matplotlib import pyplot as plt
from matplotlib_venn import venn2, venn3
from itertools import combinations
from upsetplot import UpSet

In [13]:
df = pd.read_csv(r'c:\Users\hp\Desktop\bmsis-ysp\venn_diagrams\dataset_formulas.csv')

In [17]:
df.head()

,Unnamed: 0,2023March23NegESI_17_Mars_Meteorites126p8_Sum200.csv,2023March23NegESI_20_Blank1_Aaron Burton_Sum75.csv,2023March23NegESI_9_Lon94101_Sum200.csv,2023March23NegES_10_ALH83100_Sum200.csv,2023March24NegESI_13_1MHCHO_1MCH3CHO_10mMGA_1to10_DilutionSum200.csv,2023March24NegESI_16_Mars_Meteorites_142p7_Sum500_Depletion.csv,2023March24NegESI_18_Mars_Meteorites_120p9_Sum200.csv,2023March24NegESI_19_Mars_Meteorites_115p7_Sum200.csv,2023March24NegESI_1_EET92161p20_Sum200.csv,...,2023March25NegESI_4_MIL_090657p66_Sum200.csv,2023March25NegESI_5_ALH77257p168_Sum200.csv,2023March25NegESI_8_SCO06043p38_sum200.csv,2023March25PosESI_17_Mars_Meteorites126p8_Sum200.csv,2023March26NegESI_15_Mars_Meteorites116p7_0p125TMAH_Sum200.csv,2023March26NegESI_15_Mars_Meteorites116p7_Sum500_Depletion.csv,2023March26NegESI_17_Mars_Meteorites126p8_0p125TMAH_Sum200.csv,2023March26NegESI_17_Mars_Meteorites126p8_Sum500_Depletion.csv,2023March26PosESI_15_Mars_Meteorites116p7_1percentFA_Sum200.csv,2023March26PosESI_17_Mars_Meteorites126p8_1percentFA_Sum200.csv
0,0,C 43 H 87 N 0 O 0 S 0 13C 0,C 18 H 37 N 0 O 1 S 0 13C 0,C 14 H 23 N 0 O 1 S 0 13C 0,C 37 H 13 N 0 O 0 S 0 13C 0 24Mg 1,C 21 H 15 N 0 O 0 S 0 13C 0 24Mg 1,C 34 H 53 N 0 O 0 S 0 13C 0 Na 1,C 22 H 29 N 0 O 0 S 0 13C 0 24Mg 1,C 43 H 23 N 0 O 0 S 0 13C 0,C 27 H 25 N 0 O 0 S 0 13C 0 24Mg 1,...,C 11 H 19 N 2 O 0 S 0 13C 0,C 11 H 21 N 0 O 2 S 0 13C 0,C 11 H 21 N 0 O 2 S 0 13C 0,C 14 H 23 N 0 O 0 S 0 13C 0,C 16 H 21 N 0 O 0 S 0 13C 0,C 20 H 33 N 0 O 0 S 0 13C 0 24Mg 1,C 19 H 21 N 0 O 0 S 0 13C 0,C 35 H 55 N 0 O 0 S 0 13C 0,C 18 H 25 N 0 O 0 S 0 13C 0,C 18 H 31 N 0 O 0 S 0 13C 0
1,1,C 49 H 83 N 0 O 0 S 0 13C 0,C 20 H 41 N 0 O 1 S 0 13C 0,C 15 H 25 N 0 O 1 S 0 13C 0,C 40 H 19 N 0 O 0 S 0 13C 0 24Mg 1,C 22 H 17 N 0 O 0 S 0 13C 0 24Mg 1,C 35 H 55 N 0 O 0 S 0 13C 0 Na 1,C 50 H 55 N 0 O 0 S 0 13C 0 24Mg 1,C 47 H 29 N 0 O 0 S 0 13C 0,C 23 H 15 N 0 O 0 S 0 13C 0 24Mg 1,...,C 12 H 21 N 2 O 0 S 0 13C 0,C 12 H 23 N 0 O 2 S 0 13C 0,C 12 H 23 N 0 O 2 S 0 13C 0,C 15 H 25 N 0 O 0 S 0 13C 0,C 17 H 21 N 0 O 0 S 0 13C 0,C 22 H 9 N 0 O 0 S 0 13C 0 24Mg 1,C 17 H 15 N 0 O 0 S 0 13C 0,C 18 H 15 N 0 O 0 S 0 13C 0,C 19 H 27 N 0 O 0 S 0 13C 0,C 20 H 33 N 0 O 0 S 0 13C 0
2,2,C 50 H 83 N 0 O 0 S 0 13C 0,C 15 H 29 N 0 O 1 S 0 13C 0,C 12 H 17 N 0 O 1 S 0 13C 0,C 41 H 19 N 0 O 0 S 0 13C 0 24Mg 1,C 22 H 15 N 0 O 0 S 0 13C 0 24Mg 1,C 36 H 57 N 0 O 0 S 0 13C 0 Na 1,C 42 H 37 N 0 O 0 S 0 13C 0 24Mg 1,C 43 H 19 N 0 O 0 S 0 13C 0,C 24 H 17 N 0 O 0 S 0 13C 0 24Mg 1,...,C 13 H 23 N 2 O 0 S 0 13C 0,C 13 H 25 N 0 O 2 S 0 13C 0,C 13 H 25 N 0 O 2 S 0 13C 0,C 16 H 27 N 0 O 0 S 0 13C 0,C 18 H 23 N 0 O 0 S 0 13C 0,C 23 H 9 N 0 O 0 S 0 13C 0 24Mg 1,C 18 H 17 N 0 O 0 S 0 13C 0,C 17 H 11 N 0 O 0 S 0 13C 0,C 21 H 31 N 0 O 0 S 0 13C 0,C 29 H 51 N 0 O 0 S 0 13C 0
3,3,C 57 H 77 N 0 O 0 S 0 13C 0,C 16 H 31 N 0 O 1 S 0 13C 0,C 14 H 21 N 0 O 1 S 0 13C 0,C 42 H 21 N 0 O 0 S 0 13C 0 24Mg 1,C 23 H 17 N 0 O 0 S 0 13C 0 24Mg 1,C 35 H 53 N 0 O 0 S 0 13C 0 Na 1,C 43 H 39 N 0 O 0 S 0 13C 0 24Mg 1,C 46 H 25 N 0 O 0 S 0 13C 0,C 25 H 19 N 0 O 0 S 0 13C 0 24Mg 1,...,C 14 H 25 N 2 O 0 S 0 13C 0,C 14 H 27 N 0 O 2 S 0 13C 0,C 14 H 27 N 0 O 2 S 0 13C 0,C 17 H 29 N 0 O 0 S 0 13C 0,C 19 H 25 N 0 O 0 S 0 13C 0,C 26 H 15 N 0 O 0 S 0 13C 0 24Mg 1,C 21 H 23 N 0 O 0 S 0 13C 0,C 18 H 13 N 0 O 0 S 0 13C 0,C 24 H 37 N 0 O 0 S 0 13C 0,C 15 H 21 N 0 O 0 S 0 13C 0
4,4,C 61 H 75 N 0 O 0 S 0 13C 0,C 17 H 33 N 0 O 1 S 0 13C 0,C 15 H 23 N 0 O 1 S 0 13C 0,C 43 H 23 N 0 O 0 S 0 13C 0 24Mg 1,C 24 H 19 N 0 O 0 S 0 13C 0 24Mg 1,C 48 H 57 N 0 O 0 S 0 13C 0 Na 1,C 44 H 41 N 0 O 0 S 0 13C 0 24Mg 1,C 44 H 19 N 0 O 0 S 0 13C 0,C 26 H 21 N 0 O 0 S 0 13C 0 24Mg 1,...,C 15 H 27 N 2 O 0 S 0 13C 0,C 15 H 29 N 0 O 2 S 0 13C 0,C 15 H 29 N 0 O 2 S 0 13C 0,C 18 H 31 N 0 O 0 S 0 13C 0,C 16 H 17 N 0 O 0 S 0 13C 0,C 27 H 17 N 0 O 0 S 0 13C 0 24Mg 1,C 24 H 29 N 0 O 0 S 0 13C 0,C 45 H 57 N 0 O 0 S 0 13C 0,C 25 H 39 N 0 O 0 S 0 13C 0,C 18 H 27 N 0 O 0 S 0 13C 0

In [14]:
def extract_unique_formulas(column):
    unique_formulas = set()
    for formula in column:
        unique_formulas.add(formula)
    return unique_formulas

In [ ]:
unique_formulas = {}
for col in df.columns:
    unique_formulas[col] = extract_unique_formulas(df[col])

# Prepare data for UpSet plot
unique_index = list(unique_formulas['2023March23NegESI_17_Mars_Meteorites126p8_Sum200.csv'])  # Using SampleA as the index
upset_data = pd.DataFrame(index=unique_index, columns=df.columns)

# Fill upset_data with boolean values
for col in df.columns:
    upset_data[col] = upset_data.index.isin(unique_formulas[col])

# Generate combinations of sets for intersections
combinations_list = list(combinations(df.columns, 2))

# Initialize UpSet plot correctly
upset = UpSet(upset_data, orientation='horizontal', sort_categories_by=None)

# Plot UpSet
upset.plot()
plt.title('UpSet Plot for Molecular Formulas')
plt.show()